name: Build MediumCraft Launcher

on:
  workflow_dispatch:
  push:
    paths:
      - 'HMCL/**'
      - 'HMCLCore/**'
      - 'HMCLauncher/**'
      - '.github/workflows/build-release.yml'
  pull_request:
    paths:
      - 'HMCL/**'
      - 'HMCLCore/**'
      - 'HMCLauncher/**'
      - '.github/workflows/build-release.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
          
      - name: Build HMCLauncher
        run: msbuild /p:Configuration=Release /t:Rebuild /verbosity:detailed .\HMCLauncher\
        
      - name: Copy HMCLauncher to assets
        run: Copy-Item .\HMCLauncher\Release\MediumCraftLauncher.exe -Destination .\HMCL\src\main\resources\assets\MediumCraftLauncher.exe
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: 'jdk+fx'
          
      - name: Build with Gradle
        run: .\gradlew build --no-daemon
        env:
          MICROSOFT_AUTH_ID: ${{ secrets.MICROSOFT_AUTH_ID }}
          MICROSOFT_AUTH_SECRET: ${{ secrets.MICROSOFT_AUTH_SECRET }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          
      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
        
      - name: Copy HMCLauncher to libs
        run: Copy-Item .\HMCLauncher\Release\MediumCraftLauncher.exe -Destination .\HMCL\build\libs\MediumCraftLauncher.exe
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MediumCraftLauncher-${{ env.SHORT_SHA }}
          path: HMCL/build/libs/
          
      - name: Release Files
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: HMCL/build/libs/**
          name: MediumCraft Minecraft Launcher ${{ env.SHORT_SHA }}
          body: |
            This build is not for production use. There may be bugs.
          draft: false
          tag_name: commit-${{ env.SHORT_SHA }}
          prerelease: true
          token: ${{ secrets.RELEASE_KEY }}
          generate_release_notes: true
